# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-first',
                'doc_host': 'https://spakcjl.github.io',
                'git_url': 'https://github.com/spakcjl/nbdev-first',
                'lib_path': 'nbdev_first'},
  'syms': {'nbdev_first.core': {'nbdev_first.core.foo': ('core.html#foo', 'nbdev_first/core.py')}}}
